config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  root "tabs#index"
  get 'tabs/:anchor_name' => 'tabs#show'
  resources :tabs, only: [:index, :show]
  resources :assessments, only: [:index, :show] do
    post :save
  end
  get 'search_users' => "users#search_user"
  get 'user/confirm' => "users#confirm"
  get 'search_all_users' => "users#search_all_users"

  devise_for :users, :controllers => 
    {
     :registrations => 'devise_user/registrations',
     sessions: "devise_user/sessions"
    }
  devise_scope :user do
    get "users/:id/add_image" => "devise_user/registrations#add_image"
    patch "users/:id/save_image" => "devise_user/registrations#save_image", as: "upload_profile_pic"
    get 'update_states' => "devise_user/registrations#update_states"
    get 'update_bases' => "devise_user/registrations#update_bases"
  end

  resources :users do
    member do
      get :add_contacts
      post :save_contacts
      get :add_community
      post :save_community
    end
    get :contacts, on: :collection
    post :report_bug, on: :collection
  end
  resources :content_blocks do
    resources :content_block_posts, only: [:index, :create, :new] do
      get :new_reply
      post :save_reply
      get :replies
    end
    member do
      get :index_content_block, controller: :content_block_posts
      get :contacts_and_communities, controller: :content_block_posts
      post :email, controller: :content_block_posts
    end
    post :webhook_notify, controller: :content_block_posts, on: :collection
    post :modify_video_params, controller: :content_block_posts, on: :collection
    get :check_video_upload_status, controller: :content_block_posts, on: :collection
  end
  resources :content_block_posts do
    resources :replies
  end
  resources :replies
  
  namespace :admin do
    resources :tabs do
      resources :sections do
        resources :content_blocks do
          get :get_form_partial, on: :collection 
          get :get_edit_form_partial, on: :member
          get :get_edit_form_partial, on: :collection
        end
      end
    end
    resources :assessments do
      resources :score_ranges do
        post :save_capability, on: :member
      end
      resources :questions do
        post :save_stops, on: :member
      end
    end
    resources :lpds, :path => "lpds" do
      resources :concepts, :path => "concepts"
    end 
    resources :leader_professional_development, :path => "lpds" do
      resources :concepts, :path => "concepts"
    end
  end

  resources :tags
  
  
  get 'onboarding_community_show' => "pages#onboarding_community_show"
  get 'onboarding_community_addcontact' => "pages#onboarding_community_addcontact"
  get 'lpd/:id' => "pages#lpd"
  get 'onboarding_community' => "user_communities#show"
  post "user/community/save" => "user_communities#save_community"
  post "user/allcommunity/save" => "user_communities#save_communities"
  get "user/community/:id/delete" => "user_communities#delete_community"
  get "user/community/:community_id/contact/:contact_id/delete" => "user_communities#delete_community_user"
  get "user/community/:community_id/contact/:contact_id/save" => "user_communities#add_community_user"

  #Template 1
  get 'templates/1-assignment_demands_assessment_1' => "templates#1-assignment_demands_assessment_1"
  get 'templates/1-assignment_demands_assessment_2' => "templates#1-assignment_demands_assessment_2"
  get 'templates/1-assignment_demands_assessment_3' => "templates#1-assignment_demands_assessment_3"
  get 'templates/1-assignment_demands_assessment_4' => "templates#1-assignment_demands_assessment_4"
  get 'templates/1-assignment_demands_assessment_5' => "templates#1-assignment_demands_assessment_5"
  get 'templates/1-assignment_demands_assessment_summary' => "templates#1-assignment_demands_assessment_summary"

  #Template 2
  get 'templates/2-be_a_mentor_1' => "templates#2-be_a_mentor_1"
  get 'templates/2-be_a_mentor_2' => "templates#2-be_a_mentor_2"
  get 'templates/2-be_a_mentor_3' => "templates#2-be_a_mentor_3"
  get 'templates/2-be_a_mentor_4' => "templates#2-be_a_mentor_4"
  get 'templates/2-be_a_mentor_5' => "templates#2-be_a_mentor_5"
  get 'templates/2-be_a_mentor_6' => "templates#2-be_a_mentor_6"
  get 'templates/2-be_a_mentor_7' => "templates#2-be_a_mentor_7"
  get 'templates/2-be_a_mentor_summary' => "templates#2-be_a_mentor_summary"
  
  #Template 3 
  get 'templates/3-command_unit_leader_development_scorecard_1' => 'templates#3-command_unit_leader_development_scorecard_1'
  get 'templates/3-command_unit_leader_development_scorecard_2' => 'templates#3-command_unit_leader_development_scorecard_2'
  get 'templates/3-command_unit_leader_development_scorecard_3' => 'templates#3-command_unit_leader_development_scorecard_3'
  get 'templates/3-command_unit_leader_development_scorecard_4' => 'templates#3-command_unit_leader_development_scorecard_4'
  get 'templates/3-command_unit_leader_development_scorecard_5' => 'templates#3-command_unit_leader_development_scorecard_5'
  get 'templates/3-command_unit_leader_development_scorecard_summary' => 'templates#3-command_unit_leader_development_scorecard_summary'

  #Template 4
  get 'templates/4-daily_leader_observation_planner_1' => 'templates#4-daily_leader_observation_planner_1'
  get 'templates/4-daily_leader_observation_planner_2' => 'templates#4-daily_leader_observation_planner_2'
  get 'templates/4-daily_leader_observation_planner_3' => 'templates#4-daily_leader_observation_planner_3'
  get 'templates/4-daily_leader_observation_planner_summary' => 'templates#4-daily_leader_observation_planner_summary'

  #Template 5
  get 'templates/5-getting_to_know_tool_1' => 'templates#5-getting_to_know_tool_1'
  get 'templates/5-getting_to_know_tool_2' => 'templates#5-getting_to_know_tool_2'
  get 'templates/5-getting_to_know_tool_3' => 'templates#5-getting_to_know_tool_3'
  get 'templates/5-getting_to_know_tool_4' => 'templates#5-getting_to_know_tool_4'
  get 'templates/5-getting_to_know_tool_5' => 'templates#5-getting_to_know_tool_5'
  get 'templates/5-getting_to_know_tool_6' => 'templates#5-getting_to_know_tool_6'
  get 'templates/5-getting_to_know_tool_7' => 'templates#5-getting_to_know_tool_7'
  get 'templates/5-getting_to_know_tool_summary' => 'templates#5-getting_to_know_tool_summary'
  
  #Template 6
  get 'templates/6-individual_plans_for_advancement_1' => 'templates#6-individual_plans_for_advancement_1'
  get 'templates/6-individual_plans_for_advancement_2' => 'templates#6-individual_plans_for_advancement_2'
  get 'templates/6-individual_plans_for_advancement_3' => 'templates#6-individual_plans_for_advancement_3'  
  get 'templates/6-individual_plans_for_advancement_4' => 'templates#6-individual_plans_for_advancement_4' 
  get 'templates/6-individual_plans_for_advancement_5' => 'templates#6-individual_plans_for_advancement_5'  
  get 'templates/6-individual_plans_for_advancement_6' => 'templates#6-individual_plans_for_advancement_6'
  get 'templates/6-individual_plans_for_advancement_summary' => 'templates#6-individual_plans_for_advancement_summary'  

  #Template 7
  get 'templates/7-leadership_selection_guidance_1' => 'templates#7-leadership_selection_guidance_1'
  get 'templates/7-leadership_selection_guidance_2' => 'templates#7-leadership_selection_guidance_2'
  get 'templates/7-leadership_selection_guidance_3' => 'templates#7-leadership_selection_guidance_3'  
  get 'templates/7-leadership_selection_guidance_4' => 'templates#7-leadership_selection_guidance_4' 
  get 'templates/7-leadership_selection_guidance_5' => 'templates#7-leadership_selection_guidance_5'  
  get 'templates/7-leadership_selection_guidance_6' => 'templates#7-leadership_selection_guidance_6'
  get 'templates/7-leadership_selection_guidance_7' => 'templates#7-leadership_selection_guidance_7'  
  get 'templates/7-leadership_selection_guidance_8' => 'templates#7-leadership_selection_guidance_8'
  get 'templates/7-leadership_selection_guidance_summary' => 'templates#7-leadership_selection_guidance_summary'  

  #Template 8
  get 'templates/8-learning_principles_questionaire_a_1' => 'templates#8-learning_principles_questionaire_a_1'
  get 'templates/8-learning_principles_questionaire_a_2' => 'templates#8-learning_principles_questionaire_a_2'
  get 'templates/8-learning_principles_questionaire_a_3' => 'templates#8-learning_principles_questionaire_a_3'
  get 'templates/8-learning_principles_questionaire_a_4' => 'templates#8-learning_principles_questionaire_a_4'
  get 'templates/8-learning_principles_questionaire_a_5' => 'templates#8-learning_principles_questionaire_a_5'
  get 'templates/8-learning_principles_questionaire_a_6' => 'templates#8-learning_principles_questionaire_a_6'
  get 'templates/8-learning_principles_questionaire_a_7' => 'templates#8-learning_principles_questionaire_a_7'
  get 'templates/8-learning_principles_questionaire_a_summary' => 'templates#8-learning_principles_questionaire_a_summary'

  #Template 9
  get 'templates/9-learning_principles_questionaire_b_1' => 'templates#9-learning_principles_questionaire_b_1'
  get 'templates/9-learning_principles_questionaire_b_2' => 'templates#9-learning_principles_questionaire_b_2'
  get 'templates/9-learning_principles_questionaire_b_3' => 'templates#9-learning_principles_questionaire_b_3'
  get 'templates/9-learning_principles_questionaire_b_summary' => 'templates#9-learning_principles_questionaire_b_summary'
  
  #Template 10
  get 'templates/10-training_and_professional_development_1' => 'templates#10-training_and_professional_development_1'
  get 'templates/10-training_and_professional_development_2' => 'templates#10-training_and_professional_development_2'
  get 'templates/10-training_and_professional_development_3' => 'templates#10-training_and_professional_development_3'
  get 'templates/10-training_and_professional_development_4' => 'templates#10-training_and_professional_development_4'

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :content_block_post
  belongs_to :user

  has_attached_file :video,
                    :url => ":basename.:extension",
                    :path => ":basename.:extension"

  validates_presence_of :user, :content_block_post
  validates_presence_of :content, unless: :video?
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def create
    @content_block_post = ContentBlockPost.find(params[:content_block_post_id])
    if /reply_[0-9]/.match(params[:reply][:content])
      @reply = @content_block_post.replies.where("id = ?", params[:reply][:content].split("_").last).last
    else
      @reply = @content_block_post.replies.build(reply_params)
      @reply.user = current_user
      @reply.save
      validate_video_to_be_deleted
    end
  end

  def new
    @content_block_post = ContentBlockPost.find(params[:content_block_post_id])
    init_contacts_and_communities
  end

  def destroy
    @reply = Reply.find(params[:id]).destroy
  end

  private
  def reply_params
    params.require(:reply).permit(:content)
  end

  def validate_video_to_be_deleted
    if !params[:reply_video_link].nil?
      @content_block_post.replies.where("id = ?", params[:reply_video_link].split("_").last).last.destroy rescue nil
    end
  end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.erb
<% unique_id = 'reply_' + content_block_post.id.to_s %>


  <%= form_for [content_block_post, Reply.new], remote: true, class: "new_post" do |f| %>
      <div class="community-dropdown">
        <%= image_tag "community_white.png", class: "contacts-img" %>
        POST TO: <%= select_tag :community_id, options_from_collection_for_select(@contacts_and_communities[:communities], :id, :name), id: "community_id_#{content_block_post.id}" %>
      </div>
      <div class="post-text-fields">
        <%= f.text_area :content, id: "reply_content-#{content_block_post.id}",placeholder: "Add a reply here", class: "post-content reply-input reply_content-#{unique_id}" %>
        <p id="processing-video_<%= unique_id %>"></p>
        <button type="button" class="btn btn-primary vid-button" data-toggle="modal" data-target="#myVideoModal" id="reply-video-link_<%= unique_id %>" onclick="setRecorderReplyOptions($(this));" style="display: none;">Open video recorder</button>
        <%= hidden_field_tag :reply_video_link, '', id: "reply_video_content-#{content_block_post.id}" %>
      </div>
      <div class="item-footer" id="reply-controls">
        <div class="row">
          <div class="col-xs-6 share-buttons">
            <%= link_to "<i class='fa fa-quote-left white'></i>".html_safe, "javascript:void(0);", id: "share-text-reply_#{unique_id}" %>
            <%= link_to "<i class='fa fa-video-camera'></i>".html_safe, "javascript:void(0);", id: "share-video-reply_#{unique_id}" %>
          </div>
          <div class="col-xs-6 text-right">
            <a href="javascript:void(0)" onclick="$(this).parents('form').submit();">SHARE</a>
          </div>
        </div>

      </div>

  <% end %>
<script>


  function setRecorderReplyOptions(current){
    $("input#video_title").hide();
    $("p.processing-video-reply").html("");
    $("p").removeClass('processing-video-reply');
    $(current).prev().addClass('processing-video-reply');
    $(current).prev().prev().addClass('new_reply_video_field');
    $.ajax({
      url: "<%= modify_video_params_content_blocks_path %>",
      type: "POST",
      data: "type=reply&content_block_post=<%= content_block_post.id %>"
    });
  }

  $(function(){

      $("#share-video-reply_<%= unique_id %>").click(function(){
          $("button#reply-video-link_<%= unique_id %> ").show();
          $("#reply_content-<%= content_block_post.id %>").hide();

          var reply_video_val = $("#reply_content-<%= content_block_post.id %>").val();
          if(reply_video_val && reply_video_val.match(/reply_[0-9]/)){
              $("input#reply_video_content-<%= content_block_post.id %>").val( reply_video_val );
              $("div.collapse div.reply-area div.reply-input .new_reply_video_field").val( '' );
          }

      });

      $("#share-text-reply_<%= unique_id %>").click(function(){
          $("#reply_content-<%= content_block_post.id %>").show();
          $("button#reply-video-link_<%= unique_id %>").hide();
          $("p#processing-video_<%= unique_id %>").empty();
      });
      $("#community_id_<%=content_block_post.id%>").multiselect();
  });
</script>

app/views/replies/_replies.html.erb
<div id="reply-container-<%= content_block_post.id %>">
  <% content_block_post.replies.each do |reply| %>
      <%= render partial: "replies/reply", locals: {reply: reply} %>
  <% end %>
</div>

app/views/replies/_reply.html.erb
<div class="comment-reply" id="reply-<%= reply.id %>">
  <div class="comment-header row">
    <div class="small shared-by col-md-8">
      <%= image_tag reply.user.image.url(:thumb) %>Reply from <%= reply.user.rank_last_name %>
    </div>
    <div class="col-md-4">
      <div class="delete-link pull-right">
        <% if reply.user_id == current_user.id %>
            <%= link_to "javascript:void(0)",onclick: "$(this).hide().siblings('.confirm-delete').show();", class: "init-delete" do %>
                <i class="fa fa-remove"></i>
            <% end %>
            <%= link_to reply_path(reply), method: "delete", remote: true, class: "confirm-delete", style: "display:none;" do  %>
                <span>Delete?</span>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="comment-content">
    <% if reply.video.present? %>
      <%= video_tag reply.video.url, class: 'pd15 bg-level3 on-pic', style:'width: 100%', preload: 'metadata', controls: true %>
    <% else %>
      <%= reply.content %>
    <% end %>
  </div>


  </div>

</div>

app/views/replies/create.js.erb
<% if @reply.valid? %>
    $("p.processing-video-reply").html("");
    $("#reply-container-<%= @content_block_post.id %>").append("<%= j(render partial: "reply", locals: {reply: @reply}) %>");
    $("#reply_content-<%= @content_block_post.id %>").val("");
    $("#reply-count-<%= @content_block_post.id %>").html("<%= @content_block_post.replies.count %> replies")
<% end %>

app/views/replies/destroy.js.erb
<% if @reply.destroyed? %>
    $("#reply-<%= @reply.id %>").remove();
<% end %>

app/views/replies/new.js.erb
$("#reply-form-holder").html("<%= j(render partial: "replies/form", locals: {content_block_post: @content_block_post, contacts_and_communities: @contacts_and_communities}) %>");
$(".text-collapse").collapse("show");
$("#reply-form-holder").show();
$("#post-forms").hide();