config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  root "tabs#index"
  get 'tabs/:anchor_name' => 'tabs#show'
  resources :tabs, only: [:index, :show]
  resources :assessments, only: [:index, :show] do
    post :save
  end
  get 'search_users' => "users#search_user"
  get 'user/confirm' => "users#confirm"
  get 'search_all_users' => "users#search_all_users"

  devise_for :users, :controllers => 
    {
     :registrations => 'devise_user/registrations',
     sessions: "devise_user/sessions"
    }
  devise_scope :user do
    get "users/:id/add_image" => "devise_user/registrations#add_image"
    patch "users/:id/save_image" => "devise_user/registrations#save_image", as: "upload_profile_pic"
    get 'update_states' => "devise_user/registrations#update_states"
    get 'update_bases' => "devise_user/registrations#update_bases"
  end

  resources :users do
    member do
      get :add_contacts
      post :save_contacts
      get :add_community
      post :save_community
    end
    get :contacts, on: :collection
    post :report_bug, on: :collection
  end
  resources :content_blocks do
    resources :content_block_posts, only: [:index, :create, :new] do
      get :new_reply
      post :save_reply
      get :replies
    end
    member do
      get :index_content_block, controller: :content_block_posts
      get :contacts_and_communities, controller: :content_block_posts
      post :email, controller: :content_block_posts
    end
    post :webhook_notify, controller: :content_block_posts, on: :collection
    post :modify_video_params, controller: :content_block_posts, on: :collection
    get :check_video_upload_status, controller: :content_block_posts, on: :collection
  end
  resources :content_block_posts do
    resources :replies
  end
  resources :replies
  
  namespace :admin do
    resources :tabs do
      resources :sections do
        resources :content_blocks do
          get :get_form_partial, on: :collection 
          get :get_edit_form_partial, on: :member
          get :get_edit_form_partial, on: :collection
        end
      end
    end
    resources :assessments do
      resources :score_ranges do
        post :save_capability, on: :member
      end
      resources :questions do
        post :save_stops, on: :member
      end
    end
    resources :lpds, :path => "lpds" do
      resources :concepts, :path => "concepts"
    end 
    resources :leader_professional_development, :path => "lpds" do
      resources :concepts, :path => "concepts"
    end
  end

  resources :tags
  
  
  get 'onboarding_community_show' => "pages#onboarding_community_show"
  get 'onboarding_community_addcontact' => "pages#onboarding_community_addcontact"
  get 'lpd/:id' => "pages#lpd"
  get 'onboarding_community' => "user_communities#show"
  post "user/community/save" => "user_communities#save_community"
  post "user/allcommunity/save" => "user_communities#save_communities"
  get "user/community/:id/delete" => "user_communities#delete_community"
  get "user/community/:community_id/contact/:contact_id/delete" => "user_communities#delete_community_user"
  get "user/community/:community_id/contact/:contact_id/save" => "user_communities#add_community_user"

  #Template 1
  get 'templates/1-assignment_demands_assessment_1' => "templates#1-assignment_demands_assessment_1"
  get 'templates/1-assignment_demands_assessment_2' => "templates#1-assignment_demands_assessment_2"
  get 'templates/1-assignment_demands_assessment_3' => "templates#1-assignment_demands_assessment_3"
  get 'templates/1-assignment_demands_assessment_4' => "templates#1-assignment_demands_assessment_4"
  get 'templates/1-assignment_demands_assessment_5' => "templates#1-assignment_demands_assessment_5"
  get 'templates/1-assignment_demands_assessment_summary' => "templates#1-assignment_demands_assessment_summary"

  #Template 2
  get 'templates/2-be_a_mentor_1' => "templates#2-be_a_mentor_1"
  get 'templates/2-be_a_mentor_2' => "templates#2-be_a_mentor_2"
  get 'templates/2-be_a_mentor_3' => "templates#2-be_a_mentor_3"
  get 'templates/2-be_a_mentor_4' => "templates#2-be_a_mentor_4"
  get 'templates/2-be_a_mentor_5' => "templates#2-be_a_mentor_5"
  get 'templates/2-be_a_mentor_6' => "templates#2-be_a_mentor_6"
  get 'templates/2-be_a_mentor_7' => "templates#2-be_a_mentor_7"
  get 'templates/2-be_a_mentor_summary' => "templates#2-be_a_mentor_summary"
  
  #Template 3 
  get 'templates/3-command_unit_leader_development_scorecard_1' => 'templates#3-command_unit_leader_development_scorecard_1'
  get 'templates/3-command_unit_leader_development_scorecard_2' => 'templates#3-command_unit_leader_development_scorecard_2'
  get 'templates/3-command_unit_leader_development_scorecard_3' => 'templates#3-command_unit_leader_development_scorecard_3'
  get 'templates/3-command_unit_leader_development_scorecard_4' => 'templates#3-command_unit_leader_development_scorecard_4'
  get 'templates/3-command_unit_leader_development_scorecard_5' => 'templates#3-command_unit_leader_development_scorecard_5'
  get 'templates/3-command_unit_leader_development_scorecard_summary' => 'templates#3-command_unit_leader_development_scorecard_summary'

  #Template 4
  get 'templates/4-daily_leader_observation_planner_1' => 'templates#4-daily_leader_observation_planner_1'
  get 'templates/4-daily_leader_observation_planner_2' => 'templates#4-daily_leader_observation_planner_2'
  get 'templates/4-daily_leader_observation_planner_3' => 'templates#4-daily_leader_observation_planner_3'
  get 'templates/4-daily_leader_observation_planner_summary' => 'templates#4-daily_leader_observation_planner_summary'

  #Template 5
  get 'templates/5-getting_to_know_tool_1' => 'templates#5-getting_to_know_tool_1'
  get 'templates/5-getting_to_know_tool_2' => 'templates#5-getting_to_know_tool_2'
  get 'templates/5-getting_to_know_tool_3' => 'templates#5-getting_to_know_tool_3'
  get 'templates/5-getting_to_know_tool_4' => 'templates#5-getting_to_know_tool_4'
  get 'templates/5-getting_to_know_tool_5' => 'templates#5-getting_to_know_tool_5'
  get 'templates/5-getting_to_know_tool_6' => 'templates#5-getting_to_know_tool_6'
  get 'templates/5-getting_to_know_tool_7' => 'templates#5-getting_to_know_tool_7'
  get 'templates/5-getting_to_know_tool_summary' => 'templates#5-getting_to_know_tool_summary'
  
  #Template 6
  get 'templates/6-individual_plans_for_advancement_1' => 'templates#6-individual_plans_for_advancement_1'
  get 'templates/6-individual_plans_for_advancement_2' => 'templates#6-individual_plans_for_advancement_2'
  get 'templates/6-individual_plans_for_advancement_3' => 'templates#6-individual_plans_for_advancement_3'  
  get 'templates/6-individual_plans_for_advancement_4' => 'templates#6-individual_plans_for_advancement_4' 
  get 'templates/6-individual_plans_for_advancement_5' => 'templates#6-individual_plans_for_advancement_5'  
  get 'templates/6-individual_plans_for_advancement_6' => 'templates#6-individual_plans_for_advancement_6'
  get 'templates/6-individual_plans_for_advancement_summary' => 'templates#6-individual_plans_for_advancement_summary'  

  #Template 7
  get 'templates/7-leadership_selection_guidance_1' => 'templates#7-leadership_selection_guidance_1'
  get 'templates/7-leadership_selection_guidance_2' => 'templates#7-leadership_selection_guidance_2'
  get 'templates/7-leadership_selection_guidance_3' => 'templates#7-leadership_selection_guidance_3'  
  get 'templates/7-leadership_selection_guidance_4' => 'templates#7-leadership_selection_guidance_4' 
  get 'templates/7-leadership_selection_guidance_5' => 'templates#7-leadership_selection_guidance_5'  
  get 'templates/7-leadership_selection_guidance_6' => 'templates#7-leadership_selection_guidance_6'
  get 'templates/7-leadership_selection_guidance_7' => 'templates#7-leadership_selection_guidance_7'  
  get 'templates/7-leadership_selection_guidance_8' => 'templates#7-leadership_selection_guidance_8'
  get 'templates/7-leadership_selection_guidance_summary' => 'templates#7-leadership_selection_guidance_summary'  

  #Template 8
  get 'templates/8-learning_principles_questionaire_a_1' => 'templates#8-learning_principles_questionaire_a_1'
  get 'templates/8-learning_principles_questionaire_a_2' => 'templates#8-learning_principles_questionaire_a_2'
  get 'templates/8-learning_principles_questionaire_a_3' => 'templates#8-learning_principles_questionaire_a_3'
  get 'templates/8-learning_principles_questionaire_a_4' => 'templates#8-learning_principles_questionaire_a_4'
  get 'templates/8-learning_principles_questionaire_a_5' => 'templates#8-learning_principles_questionaire_a_5'
  get 'templates/8-learning_principles_questionaire_a_6' => 'templates#8-learning_principles_questionaire_a_6'
  get 'templates/8-learning_principles_questionaire_a_7' => 'templates#8-learning_principles_questionaire_a_7'
  get 'templates/8-learning_principles_questionaire_a_summary' => 'templates#8-learning_principles_questionaire_a_summary'

  #Template 9
  get 'templates/9-learning_principles_questionaire_b_1' => 'templates#9-learning_principles_questionaire_b_1'
  get 'templates/9-learning_principles_questionaire_b_2' => 'templates#9-learning_principles_questionaire_b_2'
  get 'templates/9-learning_principles_questionaire_b_3' => 'templates#9-learning_principles_questionaire_b_3'
  get 'templates/9-learning_principles_questionaire_b_summary' => 'templates#9-learning_principles_questionaire_b_summary'
  
  #Template 10
  get 'templates/10-training_and_professional_development_1' => 'templates#10-training_and_professional_development_1'
  get 'templates/10-training_and_professional_development_2' => 'templates#10-training_and_professional_development_2'
  get 'templates/10-training_and_professional_development_3' => 'templates#10-training_and_professional_development_3'
  get 'templates/10-training_and_professional_development_4' => 'templates#10-training_and_professional_development_4'

app/controllers/content_block_posts_controller.rb
class ContentBlockPostsController < InheritedResources::Base
  skip_before_action :verify_authenticity_token, only: :webhook_notify
  skip_before_filter :authenticate_user!, only: :webhook_notify

  def create
    case params[:post_type].to_i
    when ContentBlockPost.post_types[:text]
    	@postable = PostText.create(content: params[:text])
    when ContentBlockPost.post_types[:link]
      # Links not working without http:// in front of them
      # Quick fix here
      url = params[:url]
      if /^https?:\/\//.match(url).nil?
        url = "http://" + url
      end
      @postable = PostLink.create(url: url, description: params[:description])
    when ContentBlockPost.post_types[:video]
      @postable = PostVideo.where("title IS NULL AND user_id = ?", current_user.id).last
      @postable.update_attributes(title: params[:title])
      #@postable = PostVideo.create(title: params[:title], video: params[:video])
    end
    @post = ContentBlockPost.create(
      content_block_id: params[:content_block_id],
      user_id: current_user.id,
      postable_id: @postable.id,
      postable_type: @postable.class.name,
      community_id: params[:community_id]
    )

  end
  
  def new_reply
    @reply = Reply.new
  end
  

  def save_reply
    reply = Reply.create(user_id: current_user.id, content_block_post_id: params[:content_block_post_id], content: params[:reply][:content])
    render json: { success: true }
    rescue 
      render json: { success: false }
  end
  
  def replies
    @post = ContentBlockPost.find(params[:content_block_post_id])
    @replies = @post.replies
    render json: @replies
    rescue 
      render json: { }
  end

  def index
    @content_block_posts = ContentBlockPost.includes(:postable, replies: :user)
    .where(content_block_id: params[:content_block_id]).where(community_id: community_ids)

    @content_block = ContentBlock.find(params[:content_block_id])

    init_contacts_and_communities

    respond_to do |format|
      format.js
      format.json {render json: @content_block_posts.map{|p| p.postable}}
    end
  end
  
  def index_content_block
    @content_block = ContentBlock.find(params[:id])
    posts = @content_block.content_block_posts.includes(:postable)
    render json: posts
    rescue 
      render json: { } 
  end
  
  def contacts_and_communities
    init_contacts_and_communities
    respond_to do |format|
      format.json {render json: @contacts_and_communities }
      format.html {render 'contacts_and_communities'}
      format.js
    end

  end
  
  def email
    content_block = ContentBlock.find(params[:id])
    content_block_link = "#{params[:current_tab_url]}##{content_block.anchor_name}"
    contacts_ids, communities_ids = contacts_and_communities_arrays
    communities = UserCommunity.find(communities_ids)
    users = User.find(contacts_ids)
    users_com = communities.map{|com| com.contacts.to_a }.flatten
    contacts = users + users_com
    contacts.uniq!
    if contacts.length > 0 && params[:email][:body].present?
      contacts.each do |contact|
        PostMailer.post(contact, params[:email][:body], content_block_link).deliver_later
      end
      redirect_to contacts_and_communities_content_block_path(params[:id])
    end

  end

  def destroy
    @content_block_post = ContentBlockPost.find(params[:id]).destroy
  end

  def webhook_notify
    if request.post?
    #  if Rails.env == "development"
    #    params = {"payload"=>"{\"version\":\"1.0\",\"event\":\"video_transcoded\",\"data\":{\"duration\":14,\"audioCodec\":\"AAC\",\"videoCodec\":\"H.264\",\"type\":\"MP4\",\"size\":25788,\"width\":320,\"height\":240,\"orientation\":\"landscape\",\"id\":\"2295\",\"url\":\"http:\\/\\/s1.addpipe.com\\/v\\/78e8a3a7f7194d4e357a6de8eee68122\\/vs1437059227877_963.mp4\",\"snapshotUrl\":\"https:\\/\\/s1.addpipe.com\\/v\\/78e8a3a7f7194d4e357a6de8eee68122\\/vs1437059227877_963.jpg\",\"payload\":\"user_id=1\"}}"}
    #  end
      @response   = JSON.parse( params["payload"] )
      user_param  = @response["data"]["payload"]
      video_url   = @response["data"]["url"]

      u_id        = user_param.split('=').last
      user        = User.find u_id
      video_stat  = VideoStatus.where(user_id: u_id, processed: false).last # Rails.env == "development" ? VideoStatus.last : VideoStatus.where(user_id: u_id, processed: false).last
      video_url   = video_url.split("/")
      video_name  = video_url.last
      file_name   = video_name
      file_size   = ''
      file_type   = ''
      tries       = 0
      aws_data    = Rails.application.secrets[:aws]
      s3 = Aws::S3::Client.new() #access_key_id: 'AKIAIFF4IQVIKYMEXT5Q', secret_access_key: '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'
      begin
        resp = s3.get_object( bucket: aws_data['S3_BUCKET_NAME'], key: video_name ) #do | chunk |
        file_size = resp.content_length
        file_type = resp.content_type
      rescue Aws::S3::Errors::NoSuchKey => e
        tries += 1
        Rails.logger.info "e...... #{e.inspect}"
        retry if tries <= 5
        Rails.logger.info "no dice!"
      end

      if user && video_stat
        if video_stat.video_type == "post"
          @postable = PostVideo.new( video_file_name: file_name, video_content_type: file_type, video_file_size: file_size, video_updated_at: Time.now, user_id: user.id )
        else
          @content_block_post = ContentBlockPost.find(video_stat.content_block_post_id)
          @postable = @content_block_post.replies.build(content: " ", video_file_name: file_name, video_content_type: file_type, video_file_size: file_size)
          @postable.user = user
        end

        if @postable.save
          video_stat.update_attributes(processed: true)
          Rails.logger.info "@postable+++++++++++ #{@postable.inspect}"
        else
          Rails.logger.info "@postable errors++++++++++++++#{@postable.errors.inspect}"
        end
      end

      respond_to do | format |
        format.html { render text: "Payload received and parsed successfully." }
        format.json { render json: "Payload received and parsed successfully." }
      end
    end
  end

  def check_video_upload_status
    @video_status = VideoStatus.where(user_id: current_user.id, processed: true).last
    key = 0
    if @video_status.video_type == "reply"
      @reply = Reply.where(user_id: current_user.id, content_block_post_id: @video_status.content_block_post_id).last
      key = @reply.id if @reply
    end

    respond_to do | format |
      if @video_status
        format.html { render text: @video_status.video_type + "_" + key.to_s }
      else
        format.html { render text: '' }
      end
    end
  end

  def modify_video_params
    @video_status = VideoStatus.new(user_id: current_user.id, video_type: params[:type], content_block_post_id: params[:content_block_post])

    respond_to do |format|
      if @video_status.save
        format.html { render text: true }
        format.json { render json: true }
      else
        format.html { render text: @video_status.errors }
        format.json { render json: @video_status.to_json }
      end
    end
  end

  private

  def contacts_and_communities_arrays
    contacts = {}
    (params[:contacts]||[]).map{ |y| y.split("-")}.each do |values|
      key = values[0]
      contacts[key] = []  unless contacts[key].present?
      contacts[key] << values[1]
    end
    [(contacts["contacts"]||[]), (contacts["communities"]||[])]
  end

    def content_block_post_params
      params.require(:content_block_post).permit(:content_block_id, :user_id, :postable_id, :postable_type, :content, :url, :desc )
    end


  def community_ids
    params[:filter_present] ? (params[:search][:community_ids] rescue []) : current_user.communities.collect(&:id)
  end

end

app/views/content_block_posts/_email_form.html.erb
<%= form_tag email_content_block_path(params[:content_block_id] || params[:id]), id: "email-form", remote: true, required: true do %>
    <%= hidden_field_tag :current_tab_url %>
    <div class="community-dropdown email-community">
      <%= image_tag "email_white.png", class: "contacts-img" %>
      <select id="contacts" name="contacts[]" multiple="multiple">
        <%
           index=1
           @contacts_and_communities.each do |key, values|
        %>
            <optgroup label="<%= key %>">
              <% values.each do |value| %>

                  <option value="<%= "#{key}-#{value.id}" %>"><%= value.name %></option>

              <% end %>
            </optgroup>
        <%
           index += index
           end
        %>

      </select>
    </div>

    <div>
        <%= text_area_tag "email[body]","", placeholder: "Email body", class: "post-content" %>
    </div>

<% end %>
<script>
    $(function(){
        $("#contacts").multiselect();
        // $("#current_page_url") is in /tabs/show.html.erb
        $("#current_tab_url").val($("#current_page_url").val());
    });
</script>

app/views/content_block_posts/_link.html.erb
<div class="field">
  <%= label_tag :url %><br>
  <%= text_field_tag :url %>
</div>
<div class="field">
  <%= label_tag :description %><br>
  <%= text_area_tag :description %>
 </div>

app/views/content_block_posts/_post_link.html.erb
<div class="comment-box" id="post-<%= content_block_post.id %>" style = "<%= comments_border_color(content_block_post.user_community) %>">
  <div class="comment-header row">
    <div class="small shared-by col-md-8">
      <%= image_tag content_block_post.user.image.url(:thumb) %>Shared by <%= content_block_post.user.rank_last_name %>
    </div>
    <div class="col-md-4">
      <div class="delete-link pull-right">
        <% if content_block_post.user_id == current_user.id %>

            <%= link_to "javascript:void(0)",onclick: "$(this).hide().siblings('.confirm-delete').show();", class: "init-delete" do %>
                <i class="fa fa-remove"></i>
            <% end %>
            <%= link_to content_block_post_path(content_block_post), method: "delete", remote: true, class: "confirm-delete", style: "display:none;" do  %>
                <span>Delete?</span>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="comment-content-wrapper">
    <i class="fa fa-link"></i>
    <%= link_to truncate(post_link.description, length: 32) ,  post_link.url, target: '_blank', class: "post-link", title: post_link.description %>
  </div>
  <div class="comment-footer">
    <div class="row">
      <div class="col-xs-4 reply-count">
        <span class="small" id="reply-count-<%= content_block_post.id %>"><%= content_block_post.replies.count %> replies</span>
      </div>

      <div class="col-xs-7 "></div>

      <div class="col-xs-1 text-right">
        <a href="javascript:void(0)" class="chevron" data-toggle="collapse" data-target="#comment_<%= content_block_post.id %>"><i class="fa fa-chevron-down"></i></a>
      </div>
    </div>
  </div>
  <div id="comment_<%= content_block_post.id %>" class="comment-replies collapse">
    <%= render partial: "replies/replies", locals: {content_block_post: content_block_post} %>
    <%= link_to new_content_block_post_reply_path(content_block_post), remote: true,
                id: "show-reply-form-at-top-#{content_block_post.id}",
                class: "btn btn-block solid-gold" do
    %>
        <i class="fa fa-plus"></i>
    <% end %>
  </div>

</div>

app/views/content_block_posts/_post_text.html.erb
<div class="comment-box" id="post-<%= content_block_post.id %>" style = "<%= comments_border_color(content_block_post.user_community) %>">
  <div class="comment-header row">
    <div class="small shared-by col-md-8">
      <%= image_tag content_block_post.user.image.url(:thumb) %>Shared by <%= content_block_post.user.rank_last_name %>
    </div>
    <div class="col-md-4">
      <div class="delete-link pull-right">
        <% if content_block_post.user_id == current_user.id %>

            <%= link_to "javascript:void(0)",onclick: "$(this).hide().siblings('.confirm-delete').show();", class: "init-delete" do %>
                <i class="fa fa-remove"></i>
            <% end %>
            <%= link_to content_block_post_path(content_block_post), method: "delete", remote: true, class: "confirm-delete", style: "display:none;" do  %>
                <span>Delete?</span>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="comment-content-wrapper">
    <i class="fa fa-quote-left"></i>
    <span><%= post_text.content %></span>
  </div>
  <div class="comment-footer">
    <div class="row">
      <div class="col-xs-4 reply-count">
        <span class="small" id="reply-count-<%= content_block_post.id %>"><%= content_block_post.replies.count %> replies</span>
      </div>


          <div class="col-xs-7 "></div>

      <div class="col-xs-1 text-right">
        <a href="javascript:void(0)" class="chevron" data-toggle="collapse" data-target="#comment_<%= content_block_post.id %>"><i class="fa fa-chevron-down"></i></a>
      </div>
    </div>
  </div>
  <div id="comment_<%= content_block_post.id %>" class="comment-replies collapse">
    <%= render partial: "replies/replies", locals: {content_block_post: content_block_post} %>

    <%= link_to new_content_block_post_reply_path(content_block_post), remote: true,
                id: "show-reply-form-at-top-#{content_block_post.id}",
                class: "btn btn-block solid-gold" do
    %>
        <i class="fa fa-plus"></i>
    <% end %>
  </div>

</div>

app/views/content_block_posts/_post_video.html.erb
<div class="comment-box" id="post-<%= content_block_post.id %>" style = "<%= comments_border_color(content_block_post.user_community) %>">
  <div class="comment-header row">
    <div class="small shared-by col-md-8">
      <%= image_tag content_block_post.user.image.url(:thumb) %>Shared by <%= content_block_post.user.rank_last_name %>
    </div>
    <div class="col-md-4">
      <div class="delete-link pull-right">
        <% if content_block_post.user_id == current_user.id %>

            <%= link_to "javascript:void(0)",onclick: "$(this).hide().siblings('.confirm-delete').show();", class: "init-delete" do %>
                <i class="fa fa-remove"></i>
            <% end %>
            <%= link_to content_block_post_path(content_block_post), method: "delete", remote: true, class: "confirm-delete", style: "display:none;" do  %>
                <span>Delete?</span>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="comment-content-wrapper">
    <i class="fa fa-video-camera"></i>
    <%= link_to post_link.title,  "javascript:void(0);", target: '_blank', class: "post-link", title: post_link.title %>
    <%= video_tag post_link.video.url, class: 'pd15 bg-level3 on-pic', style:'width: 100%', preload: 'metadata', controls: true %>
  </div>
  <div class="comment-footer">
    <div class="row">
      <div class="col-xs-4 reply-count">
        <span class="small" id="reply-count-<%= content_block_post.id %>"><%= content_block_post.replies.count %> replies</span>
      </div>

      <div class="col-xs-7 "></div>

      <div class="col-xs-1 text-right">
        <a href="javascript:void(0)" class="chevron" data-toggle="collapse" data-target="#comment_<%= content_block_post.id %>"><i class="fa fa-chevron-down"></i></a>
      </div>
    </div>
  </div>
  <div id="comment_<%= content_block_post.id %>" class="comment-replies collapse">
    <%= render partial: "replies/replies", locals: {content_block_post: content_block_post} %>
    <%= link_to new_content_block_post_reply_path(content_block_post), remote: true,
                id: "show-reply-form-at-top-#{content_block_post.id}",
                class: "btn btn-block solid-gold" do
    %>
        <i class="fa fa-plus"></i>
    <% end %>

  </div>

</div>

app/views/content_block_posts/contacts_and_communities.html.erb
<%= form_tag(email_content_block_path) do%>
  <%= label_tag :communities %><br>
  <% @contacts_and_communities[:communities].each do |com|%>
    <div class="field">
      <%= check_box_tag 'communities[]', com.id %>
      <%= com.name%>
    </div>
  <%end%>
  <%= label_tag :contacts %><br>
  <% @contacts_and_communities[:contacts].each do |contact|%>
    <div class="field">
      <%= check_box_tag 'contacts[]', contact.id %>
      <%= contact.name%>
    </div>
  <%end%>
  <div class="field">
    <%= label_tag :content %><br>
    <%= text_area_tag :content %>
  </div>
  <%=submit_tag 'SendEmail'%>
<%end%>

app/views/content_block_posts/contacts_and_communities.js.erb
$("#email-form-container").html("<%= j(render partial: "email_form") %>");

app/views/content_block_posts/create.js.erb
<% if @postable.valid? %>
    $(".post-content").val("");
    var postContainer = $("#post-container-<%= params[:content_block_id] %>");
    $("p.processing-video-reply").html("");
    <% if @postable.is_a?(PostText) %>
        postContainer.prepend("<%= j(render partial: "post_text", locals: {post_text: @postable, content_block_post: @post}) %>");
    <% elsif @postable.is_a?(PostLink) %>
        postContainer.prepend("<%= j(render partial: "post_link", locals: {post_link: @postable, content_block_post: @post}) %>");
    <% elsif @postable.is_a?(PostVideo) %>
        postContainer.prepend("<%= j(render partial: "post_video", locals: {post_link: @postable, content_block_post: @post}) %>");
    <% end %>
<% end %>

app/views/content_block_posts/destroy.js.erb
<% if @content_block_post.destroyed? %>
    $("#post-<%= @content_block_post.id %>").remove();
<% end %>

app/views/content_block_posts/edit.html.erb
<h1>Editing content_block_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @content_block_post %> |
<%= link_to 'Back', content_block_posts_path %>

app/views/content_block_posts/index.js.erb
<% if params[:filter_present].present? %>
    $("#post-container-<%= @content_block.id %>").html("<%= j(render partial: "tabs/posts" )%>");
<% else %>
    $("#right-drawer-body").html("<%= j(render partial: "tabs/right_drawer_body") %>");
<% end %>

app/views/content_block_posts/new.html.erb
<h1>New content_block_post</h1>

<%= render 'form' %>

app/views/content_block_posts/new_reply.html.erb
<%= form_for(@reply, :url => content_block_post_save_reply_path) do |f| %>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>