config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  root "tabs#index"
  get 'tabs/:anchor_name' => 'tabs#show'
  resources :tabs, only: [:index, :show]
  resources :assessments, only: [:index, :show] do
    post :save
  end
  get 'search_users' => "users#search_user"
  get 'user/confirm' => "users#confirm"
  get 'search_all_users' => "users#search_all_users"

  devise_for :users, :controllers => 
    {
     :registrations => 'devise_user/registrations',
     sessions: "devise_user/sessions"
    }
  devise_scope :user do
    get "users/:id/add_image" => "devise_user/registrations#add_image"
    patch "users/:id/save_image" => "devise_user/registrations#save_image", as: "upload_profile_pic"
    get 'update_states' => "devise_user/registrations#update_states"
    get 'update_bases' => "devise_user/registrations#update_bases"
  end

  resources :users do
    member do
      get :add_contacts
      post :save_contacts
      get :add_community
      post :save_community
    end
    get :contacts, on: :collection
    post :report_bug, on: :collection
  end
  resources :content_blocks do
    resources :content_block_posts, only: [:index, :create, :new] do
      get :new_reply
      post :save_reply
      get :replies
    end
    member do
      get :index_content_block, controller: :content_block_posts
      get :contacts_and_communities, controller: :content_block_posts
      post :email, controller: :content_block_posts
    end
    post :webhook_notify, controller: :content_block_posts, on: :collection
    post :modify_video_params, controller: :content_block_posts, on: :collection
    get :check_video_upload_status, controller: :content_block_posts, on: :collection
  end
  resources :content_block_posts do
    resources :replies
  end
  resources :replies
  
  namespace :admin do
    resources :tabs do
      resources :sections do
        resources :content_blocks do
          get :get_form_partial, on: :collection 
          get :get_edit_form_partial, on: :member
          get :get_edit_form_partial, on: :collection
        end
      end
    end
    resources :assessments do
      resources :score_ranges do
        post :save_capability, on: :member
      end
      resources :questions do
        post :save_stops, on: :member
      end
    end
    resources :lpds, :path => "lpds" do
      resources :concepts, :path => "concepts"
    end 
    resources :leader_professional_development, :path => "lpds" do
      resources :concepts, :path => "concepts"
    end
  end

  resources :tags
  
  
  get 'onboarding_community_show' => "pages#onboarding_community_show"
  get 'onboarding_community_addcontact' => "pages#onboarding_community_addcontact"
  get 'lpd/:id' => "pages#lpd"
  get 'onboarding_community' => "user_communities#show"
  post "user/community/save" => "user_communities#save_community"
  post "user/allcommunity/save" => "user_communities#save_communities"
  get "user/community/:id/delete" => "user_communities#delete_community"
  get "user/community/:community_id/contact/:contact_id/delete" => "user_communities#delete_community_user"
  get "user/community/:community_id/contact/:contact_id/save" => "user_communities#add_community_user"

  #Template 1
  get 'templates/1-assignment_demands_assessment_1' => "templates#1-assignment_demands_assessment_1"
  get 'templates/1-assignment_demands_assessment_2' => "templates#1-assignment_demands_assessment_2"
  get 'templates/1-assignment_demands_assessment_3' => "templates#1-assignment_demands_assessment_3"
  get 'templates/1-assignment_demands_assessment_4' => "templates#1-assignment_demands_assessment_4"
  get 'templates/1-assignment_demands_assessment_5' => "templates#1-assignment_demands_assessment_5"
  get 'templates/1-assignment_demands_assessment_summary' => "templates#1-assignment_demands_assessment_summary"

  #Template 2
  get 'templates/2-be_a_mentor_1' => "templates#2-be_a_mentor_1"
  get 'templates/2-be_a_mentor_2' => "templates#2-be_a_mentor_2"
  get 'templates/2-be_a_mentor_3' => "templates#2-be_a_mentor_3"
  get 'templates/2-be_a_mentor_4' => "templates#2-be_a_mentor_4"
  get 'templates/2-be_a_mentor_5' => "templates#2-be_a_mentor_5"
  get 'templates/2-be_a_mentor_6' => "templates#2-be_a_mentor_6"
  get 'templates/2-be_a_mentor_7' => "templates#2-be_a_mentor_7"
  get 'templates/2-be_a_mentor_summary' => "templates#2-be_a_mentor_summary"
  
  #Template 3 
  get 'templates/3-command_unit_leader_development_scorecard_1' => 'templates#3-command_unit_leader_development_scorecard_1'
  get 'templates/3-command_unit_leader_development_scorecard_2' => 'templates#3-command_unit_leader_development_scorecard_2'
  get 'templates/3-command_unit_leader_development_scorecard_3' => 'templates#3-command_unit_leader_development_scorecard_3'
  get 'templates/3-command_unit_leader_development_scorecard_4' => 'templates#3-command_unit_leader_development_scorecard_4'
  get 'templates/3-command_unit_leader_development_scorecard_5' => 'templates#3-command_unit_leader_development_scorecard_5'
  get 'templates/3-command_unit_leader_development_scorecard_summary' => 'templates#3-command_unit_leader_development_scorecard_summary'

  #Template 4
  get 'templates/4-daily_leader_observation_planner_1' => 'templates#4-daily_leader_observation_planner_1'
  get 'templates/4-daily_leader_observation_planner_2' => 'templates#4-daily_leader_observation_planner_2'
  get 'templates/4-daily_leader_observation_planner_3' => 'templates#4-daily_leader_observation_planner_3'
  get 'templates/4-daily_leader_observation_planner_summary' => 'templates#4-daily_leader_observation_planner_summary'

  #Template 5
  get 'templates/5-getting_to_know_tool_1' => 'templates#5-getting_to_know_tool_1'
  get 'templates/5-getting_to_know_tool_2' => 'templates#5-getting_to_know_tool_2'
  get 'templates/5-getting_to_know_tool_3' => 'templates#5-getting_to_know_tool_3'
  get 'templates/5-getting_to_know_tool_4' => 'templates#5-getting_to_know_tool_4'
  get 'templates/5-getting_to_know_tool_5' => 'templates#5-getting_to_know_tool_5'
  get 'templates/5-getting_to_know_tool_6' => 'templates#5-getting_to_know_tool_6'
  get 'templates/5-getting_to_know_tool_7' => 'templates#5-getting_to_know_tool_7'
  get 'templates/5-getting_to_know_tool_summary' => 'templates#5-getting_to_know_tool_summary'
  
  #Template 6
  get 'templates/6-individual_plans_for_advancement_1' => 'templates#6-individual_plans_for_advancement_1'
  get 'templates/6-individual_plans_for_advancement_2' => 'templates#6-individual_plans_for_advancement_2'
  get 'templates/6-individual_plans_for_advancement_3' => 'templates#6-individual_plans_for_advancement_3'  
  get 'templates/6-individual_plans_for_advancement_4' => 'templates#6-individual_plans_for_advancement_4' 
  get 'templates/6-individual_plans_for_advancement_5' => 'templates#6-individual_plans_for_advancement_5'  
  get 'templates/6-individual_plans_for_advancement_6' => 'templates#6-individual_plans_for_advancement_6'
  get 'templates/6-individual_plans_for_advancement_summary' => 'templates#6-individual_plans_for_advancement_summary'  

  #Template 7
  get 'templates/7-leadership_selection_guidance_1' => 'templates#7-leadership_selection_guidance_1'
  get 'templates/7-leadership_selection_guidance_2' => 'templates#7-leadership_selection_guidance_2'
  get 'templates/7-leadership_selection_guidance_3' => 'templates#7-leadership_selection_guidance_3'  
  get 'templates/7-leadership_selection_guidance_4' => 'templates#7-leadership_selection_guidance_4' 
  get 'templates/7-leadership_selection_guidance_5' => 'templates#7-leadership_selection_guidance_5'  
  get 'templates/7-leadership_selection_guidance_6' => 'templates#7-leadership_selection_guidance_6'
  get 'templates/7-leadership_selection_guidance_7' => 'templates#7-leadership_selection_guidance_7'  
  get 'templates/7-leadership_selection_guidance_8' => 'templates#7-leadership_selection_guidance_8'
  get 'templates/7-leadership_selection_guidance_summary' => 'templates#7-leadership_selection_guidance_summary'  

  #Template 8
  get 'templates/8-learning_principles_questionaire_a_1' => 'templates#8-learning_principles_questionaire_a_1'
  get 'templates/8-learning_principles_questionaire_a_2' => 'templates#8-learning_principles_questionaire_a_2'
  get 'templates/8-learning_principles_questionaire_a_3' => 'templates#8-learning_principles_questionaire_a_3'
  get 'templates/8-learning_principles_questionaire_a_4' => 'templates#8-learning_principles_questionaire_a_4'
  get 'templates/8-learning_principles_questionaire_a_5' => 'templates#8-learning_principles_questionaire_a_5'
  get 'templates/8-learning_principles_questionaire_a_6' => 'templates#8-learning_principles_questionaire_a_6'
  get 'templates/8-learning_principles_questionaire_a_7' => 'templates#8-learning_principles_questionaire_a_7'
  get 'templates/8-learning_principles_questionaire_a_summary' => 'templates#8-learning_principles_questionaire_a_summary'

  #Template 9
  get 'templates/9-learning_principles_questionaire_b_1' => 'templates#9-learning_principles_questionaire_b_1'
  get 'templates/9-learning_principles_questionaire_b_2' => 'templates#9-learning_principles_questionaire_b_2'
  get 'templates/9-learning_principles_questionaire_b_3' => 'templates#9-learning_principles_questionaire_b_3'
  get 'templates/9-learning_principles_questionaire_b_summary' => 'templates#9-learning_principles_questionaire_b_summary'
  
  #Template 10
  get 'templates/10-training_and_professional_development_1' => 'templates#10-training_and_professional_development_1'
  get 'templates/10-training_and_professional_development_2' => 'templates#10-training_and_professional_development_2'
  get 'templates/10-training_and_professional_development_3' => 'templates#10-training_and_professional_development_3'
  get 'templates/10-training_and_professional_development_4' => 'templates#10-training_and_professional_development_4'

app/models/content_block.rb
class ContentBlock < ActiveRecord::Base
  #associations
  belongs_to :section
  belongs_to :block, :polymorphic => true
  has_many :content_block_posts
  acts_as_list #scope: :section
  #validations
  validates :title, :anchor_name,  
    :quick_navigation_title, :spacing, presence: {message: "cannot be blank"} 

  validates :spacing, numericality: { :greater_than_or_equal_to => 0 }
  #validates :url, url: true
  acts_as_ordered_taggable

  def self.save_block(params)
    if params[:id]
      @content_block = ContentBlock.find(params[:id])
      type = @content_block.block
    else  
      @content_block = ContentBlock.new
      case params[:type].to_i
        when AdminData::Block::TextBox
          type = TextBox.new
        when AdminData::Block::Title
          type = Title.new    
        when AdminData::Block::Template
          type = Template.new
        when AdminData::Block::VideoHorizontal
          type = VideoHorizontal.new
        when AdminData::Block::VideoVertical
          type = VideoVertical.new
        when AdminData::Block::Ttp
          type = Ttp.new
        when AdminData::Block::Introduction
          type = Introduction.new
        when AdminData::Block::Lpd
          type = Lpd.new
        else
      end
       
    end

   type.assign_params(params)
    if type.valid?
      if type.save
        @content_block = assign_params(@content_block, type, params)
        if @content_block.valid?
          @content_block.save
        end
      else
        @content_block.valid?
        @content_block.errors.messages.merge!(type.errors.messages)
      end
    else
      @content_block = assign_params(@content_block, type, params)
      @content_block.valid?
      @content_block.errors.messages.merge!(type.errors.messages)
    end
    return @content_block, type
  end
  
  def self.assign_params(content_block, type, params)
    content_block.block = type
    content_block.title = params[:title]
    content_block.anchor_name = params[:anchor_name]
    content_block.quick_navigation_title = params[:quick_navigation_title]
    content_block.url = params[:url]
    content_block.spacing = params[:spacing] 
    content_block.section_id = params[:section_id] 
    if !["2", "3", "7"].include? type
      content_block.tag_list = params[:tag_list]
    end
    content_block
  end
end

app/views/admin/content_blocks/_form.html.erb
<%= render partial: 'load_form_script' %>
<%#= javascript_include_tag "application" %>
<% if params[:id].nil?%>
  <%if @type.blank?%>
    <%= select_tag "type", options_for_select(AdminData::Block::Types), 
      {:onchange => "load_form(this.options[this.selectedIndex].value);", 
      prompt: 'Select Type'} %>
  <%else%>
    <%= select_tag "type", options_for_select(AdminData::Block::Types, AdminData::Block::Types[@type.to_i - 1]), 
      {:onchange => "load_form(this.options[this.selectedIndex].value)", 
      prompt: 'Select Type'} %>
    <div>   
      <script>
        load_form("<%= @type%>");
      </script>
    </div>
  <%end%>
<%else%>
  <div id="edit_form"> 
    <script>
      load_edit_form();       
    </script>
  </div>
<%end%>

<div id="form"></div>

app/views/admin/content_blocks/_form_content_block_common.html.erb
<% if @errors.any? %>
  <div id="error_explanation" class="error-box">
    <h2><%= pluralize(@errors.count, "error") %> prohibited this content_block from being saved:</h2>

    <ul>
    <% @errors.each do |message| %>
      <li><b><%= message[0] %></b>: <%= message[1][0]%></li>
    <% end %>
    </ul>
  </div>
<% end %>
<input type="hidden" value="<%=@parent_anchor%>" id="tab_anchor" />
<div style="float:left" class="common-block">
  <%= hidden_field_tag :type, @value %>
  <div class="field">
    <div class="left">
      <%= label_tag :title %>
      <%= text_field_tag :title, @content_block["title"] %>
    </div>
    <div class="right" >
      <%= label_tag :anchor_name %>
      <%= text_field_tag :anchor_name, @content_block["anchor_name"],class:"anchor_box" ,onkeyup:"update_url(this,'url_value')"%>
    </div>
  </div>
  <div class="field">
    <div class="right">
      <%= label_tag :url %>
      <%= label_tag "",nil, class:"url_value",style:"width:auto;font-weight:normal" %>
    </div>
  </div>
  <div class="field">
    <div class="left">
      <%= label_tag :bottom_spacing %>
      <%= number_field_tag :spacing, @content_block["spacing"], min: 0 %>
    </div>
    <div class="right">
      <%= label_tag :quick_navigation_title %>
      <%= text_field_tag :quick_navigation_title, @content_block["quick_navigation_title"] %>
    </div>
  </div>
  <%if !["2", "3", "7"].include? @value.to_s %> 
    <div class="field">
      <div class="left">
        <%= label_tag :tag %>
        <%= text_field_tag :tag_list, @content_block.try(:tag_list).to_s %>
      </div>
    </div>
  <%end%>
</div>

app/views/admin/content_blocks/_form_introduction.html.erb
<%= form_tag(admin_tab_section_content_blocks_path) do |f| %>
  <%= render(:partial => 'form_content_block_common')%>
  <div class="content_block">
    <div class="field">
      <div class="left">
        <%= label_tag :upper_spacing %>
        <%= number_field_tag :space_upper, @block["space_upper"], min: 0 %>
      </div>
    </div>
  <div class="div-block">
    <h3><b>Title</b></h3>
    <div class="field-row">
      <div class="number">
          <%= label_tag :width %><br>
          <%= number_field_tag :width, @block["width"], min: 0 %>%
      </div>
      <div class="number">
          <%= label_tag :alpha %><br>
          <%= number_field_tag :alpha, @block["alpha"], min: 0 %>%
      </div>
      <div class="text-field">
          <%= label_tag :bg_color %><br>
          <%= text_field_tag :bg_color, @block["bg_color"] %>
      </div>
      <div class="number">
          <%= label_tag :position %><br>
          <%= number_field_tag :position, @block["position"], min: 0 %>%
      </div>
    </div>
     <div class="text_area">
       <%= label_tag :text %><br>
       <%= text_area_tag :text, @block["text"]%>
     </div>
  </div>

 <div class="div-block">
   <h3><b>Body</b></h3>
   <div class="field-row">
      <div class="number">
          <%= label_tag :width %><br>
          <%= number_field_tag :body_width, @block["body_width"], min: 0 %>%
      </div>
      <div class="number">
          <%= label_tag :alpha %><br>
          <%= number_field_tag :body_alpha, @block["body_alpha"], min: 0 %>%
      </div>
   </div>   
   <div class="text_area">
    <%= label_tag :body_text %><br>
    <%= text_area_tag :body_text, @block["body_text"]%>
   </div>

  <div class="actions">
    <%= button_tag :save %>
  </div>
 </div> 
<% end %>
</div>

app/views/admin/content_blocks/_form_lpd.html.erb
<%= form_tag(admin_tab_section_content_blocks_path) do |f| %>
  <%= render(:partial => 'form_content_block_common')%>
  <div class="content_block">
    <div class="div-block">
      <div class="field-row">
        <div class="number">
          <div>
            <%= radio_button_tag :design, "Light",
              (@block["design"] == "Light") %> Light Design
          </div>
          <div>
            <%= radio_button_tag :design, "Right", 
              (@block["design"] == "Right")%>Right Design
          </div>
        </div>
        <div class="bigtext">
          <%= label_tag :subject %><br>
            <%= text_field_tag :subject, @block["subject"] %>
        </div>
        <div class="bigtext">
          <%= label_tag :subtitle %><br>
          <%= text_field_tag :subtitle, @block["subtitle"] %>
        </div>
      </div>
      <div class="field-row">
        <div class="file-field" style="padding-left:100px">
          <%= label_tag :background_image %><br>
          <%= file_field_tag :image, :hint => @block["image_file_name"] %><br>
          <%= @block["image_file_name"] %>
        </div>
        <div class="bigtext">
          <%= label_tag :time %><br>
          <%= text_field_tag :time, @block["time"] %>
        </div>
      </div>
      <div class="field-row">
        <div class="bigtext">
          <%= label_tag :lpd_anchor_name %><br>
          <%= text_field_tag :lpd_anchor_name, @block["lpd_anchor_name"] %>
        </div>
      </div>
      <div class="text_area">
        <%= label_tag :description %><br>
        <%= text_area_tag :description, @block["description"] %>
      </div>
      <div class="bigtext">
        <%= label_tag :select_lpd %><br>
        <%=  select_tag "lpd", options_from_collection_for_select(@lpds, "id", "title", @block["leader_professional_development_id"]) %>
      </div>
    </div>
    <div class="div-block">
      <%= button_tag :save %>
    </div>
  </div>   
<% end %>

app/views/admin/content_blocks/_form_resource.html.erb
<%= form_tag(admin_section_content_blocks_path) do |f| %>
  <%= render(:partial => 'form_content_block_common')%>
  <div class="field">
    <%= label_tag :image %><br>
    <%= file_field_tag :image, :hint => @block.image_file_name %><br>
  </div>
  <div class="actions">
    <%= button_tag :save %>
  </div>
<% end %>

app/views/admin/content_blocks/_form_template.html.erb
<%= form_tag(admin_tab_section_content_blocks_path) do |f| %>
  <%= render(:partial => 'form_content_block_common')%>
  <div class="content_block">
    <div class="div-block">
      <div class="float-element">
      <div class="left">
      <div class="field-row">
        <div class="number">
          <%= label_tag :width %><br>
          <%= number_field_tag :width, @block["width"], min: 0 %>%
        </div>
        <div class="number">
          <%= label_tag :alpha %><br>
          <%= number_field_tag :alpha, @block["alpha"], min: 0 %>%
        </div>
      </div>
      <div class="field-row">
        <%= label_tag :resource_image %><br>
        <%= file_field_tag :image, :hint => @block["image_file_name"] %><br>
        <%= @block["image_file_name"] %>
      </div>
      </div>
      <div class="right">
         <div class="text_area_template">
          <%= label_tag :text %><br>
          <%= text_area_tag :text, @block["text"] %>
         </div>
          <div class="bigtext">
            <%= label_tag :select_template_type %><br>
            <%=  select_tag "template_type", options_from_collection_for_select(MasterTemplate.exclude_templates, "id", "name", @block["master_template_id"]) %>
          </div>
      </div>
      </div>
      <div style="text-align:center">
        <div class="actions">
         <%= button_tag :save %>
        </div>
      </div>
      </div>    
  </div>




<% end %>

app/views/admin/content_blocks/_form_text_box.html.erb
<%= form_tag(admin_tab_section_content_blocks_path) do |f| %>
  <%= render(:partial => 'form_content_block_common')%>
  <div class="content_block">
   <div class="div-block">
    <div class="field-row">
      <div class="number">
          <%= label_tag :width %><br>
          <%= number_field_tag :width, @block["width"], min: 0 %>%
      </div>
      <div class="number">
          <%= label_tag :alpha %><br>
          <%= number_field_tag :alpha, @block["alpha"], min: 0 %>%
      </div>
    </div>

   <div class="text_area">
     <%= label_tag :text_box_text %><br>
     <%= text_area_tag :text, @block["text"] %>
   </div>
   <div class="actions">
    <%= button_tag :save %>
   </div>
   </div>
</div>
<% end %>

app/views/admin/content_blocks/_form_title.html.erb
<%= form_tag(admin_tab_section_content_blocks_path) do |f| %>
  <%= render(:partial => 'form_content_block_common')%>
  <div class="content_block">
    <div class="div-block">
      <div class="field-row">
        <div class="number">
          <%= label_tag :width %><br>
          <%= number_field_tag :width, @block["width"], min: 0 %>%
        </div>
        <div class="number">
         <%= label_tag :justification %><br>
         <%= select_tag :justification, options_for_select(AdminData::Justification::Types, @block["justification"])%>
        </div>
        <div class="number">
          <%= label_tag :animation %><br>
          <%= select_tag "animation", 
          options_for_select(AdminData::Animation::Types, @block["animation"]) 
          %>
        </div>
      </div>
      <div class="text_area">
       <%= label_tag :title_text %><br>
       <%= text_area_tag :text, @block["text"] %>
      </div>
      <div class="actions">
       <%= submit_tag %>
      </div>
    </div>
  </div>
  <% end %>

app/views/admin/content_blocks/_form_ttp.html.erb
<%= form_tag(admin_tab_section_content_blocks_path) do |f| %>
  <%= render(:partial => 'form_content_block_common')%>
 <div class="content_block">
   <div class="div-block">
     <div class="field-row">
        <%= label_tag :audio %><br>
        <%= file_field_tag :audio %><br>
        <%= @block["audio_file_name"] %>
     </div>
       <div class="text_area">
        <%= label_tag :TTP_text %><br>
        <%= text_area_tag :text, @block["text"] %>
       </div>
   </div>
  <div class="div-block">
    <%= button_tag :save %>
  </div>
 </div>  



<% end %>

app/views/admin/content_blocks/_form_video_horizontal.html.erb
<%= form_tag(admin_tab_section_content_blocks_path) do |f| %>
  <%= render(:partial => 'form_content_block_common')%>
  <div class="content_block">
     <div class="div-block">
        <h3><b>Text</b></h3>
        <div class="field-row">
          <div class="number">
            <%= label_tag :width %><br>
            <%= number_field_tag :width, @block["width"], min: 0 %>%
          </div>
           <div class="number">
            <%= label_tag :alpha %><br>
            <%= number_field_tag :alpha, @block["alpha"], min: 0 %>%
          </div>
          <div>
            <div>
               <%= radio_button_tag :place_text, "Right",
               (@block["place_text"] == "Right") %> Place text Right of Video
            </div>
            <div>
              <%= radio_button_tag :place_text, "Left", 
                (@block["place_text"] == "Left")%>Place text Left of Video
            </div>
            <div >
              <%= check_box_tag :hide_text, :true, @block["hide_text"] %>
              <%= label_tag :hide_text %>
            </div>
          </div>
        </div>
          <div class="text_area">
            <%= label_tag :text_box_text %><br>
            <%= text_area_tag :text, @block["text"] %>
          </div>
      </div>
      <div class="div-block">
        <div class="directUpload">
        <h3><b>Video</b></h3>
        <div class="field-row">
          <div class="number">
           <%= label_tag :width %><br>
           <%= number_field_tag :video_width, @block["video_width"], min: 0 %>%
          </div>
          <div class="number">
          <%= label_tag :video_file %><br>
          <%= file_field_tag :video %><br>
          <%= @block["video_url"] %>
        </div>
      </div>
      </div>
      <div class="div-block">
        <%= button_tag :save %>
      </div>
  </div>      

<% end %>
<% if @block["video_url"].present?%>
  <% url = @block["video_url"].split("/")%>
  <% @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/video_horizantal/#{url[4]}/${filename}", 
        success_action_status: '201'
      ) %>
<%end%>

app/views/admin/content_blocks/_form_video_vertical.html.erb
<%= form_tag(admin_tab_section_content_blocks_path) do |f| %>
  <%= render(:partial => 'form_content_block_common')%>
  <div class="content_block">
     <div class="div-block">
        <h3><b>Text</b></h3>
        <div class="field-row">
          <div class="number">
            <%= label_tag :width %><br>
            <%= number_field_tag :width, @block["width"], min: 0 %>%
          </div>
          <div class="number">
            <%= label_tag :alpha %><br>
            <%= number_field_tag :alpha, @block["alpha"], min: 0 %>%
          </div>
          <div>
           <div>
            <%= radio_button_tag :place_text, "Right",
            (@block["place_text"] == "Right") %> Place text Below of Video
          </div>
          <div>
            <%= radio_button_tag :place_text, "Left", 
            (@block["place_text"] == "Left")%>Place text Above of Video
          </div>
          <div>
            <%= check_box_tag :hide_text, :true, @block["hide_text"] %>
            <%= label_tag :hide_text %>
          </div>
          </div>
        </div>
         <div class="text_area">
         <%= label_tag :text_box_text %><br>
         <%= text_area_tag :text, @block["text"] %>
         </div>
     </div>
      <div class="div-block">
        <div class="directUpload">
        <h3><b>Video</b></h3>
        <div class="field-row">
          <div class="number">
           <%= label_tag :width %><br>
           <%= number_field_tag :video_width, @block["video_width"], min: 0 %>%
          </div>
          <div class="number">
          <%= label_tag :video_file %><br>
          <%= file_field_tag :video %><br>
          <%= @block["video_url"] %>
        </div>
      </div>
      </div>

      </div>  
        <div class="div-block">
        <%= button_tag :save %>
       </div>
  </div>   
<% end %>
<% if @block["video_url"].present?%>
  <% url = @block["video_url"].split("/")%>
  <% @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/video_vertical/#{url[4]}/${filename}", 
        success_action_status: '201'
      ) %>
<%end%>

app/views/admin/content_blocks/_load_form_script.html.erb
<script>
  function load_form(value)
  {
    $.ajax({
    url: "get_form_partial",
    cache: false,
    data: {type: value, errors: '<%= @errors.to_json.html_safe%>', cb: '<%= @cb.to_json.html_safe%>', type_data: '<%= @type_data.to_json.html_safe%>'}
   });
  }
  function load_edit_form()
    {
      $.ajax({
       url: "get_edit_form_partial",
       cache: false,
       data: {id: '<%= params[:id]%>', errors: '<%= @errors.to_json.html_safe%>', cb: '<%= @cb.to_json.html_safe%>', type_data: '<%= @type_data.to_json.html_safe%>'}
      });
    }
</script>

app/views/admin/content_blocks/get_edit_form_partial.js.erb
//$("#edit_form").html("<div class= "panel" style="width:100px"> <h3> <%= @type[0] %></h3></div>")
$("#form").html("<%= escape_javascript(render partial: @partial ) %>")
<% if ((@partial =='form_video_horizontal') || (@partial =='form_video_vertical'))%>
$( document ).ajaxComplete(function( event,request, settings ) {
    $(function() {
  <%= render :partial => 'admin/file_upload'%>
  file_upload();
});
});
<%end%>

app/views/admin/content_blocks/get_form_partial.js.erb
$("#form").html("<%= escape_javascript(render partial: @partial ) %>")
<% if (@partial =='form_video_horizontal') || (@partial =='form_video_vertical')%>
$( document ).ajaxComplete(function( event,request, settings ) {
    $(function() {
  <%= render :partial => 'admin/file_upload'%>
  file_upload();
  });
});
<%end%>