config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  root "tabs#index"
  get 'tabs/:anchor_name' => 'tabs#show'
  resources :tabs, only: [:index, :show]
  resources :assessments, only: [:index, :show] do
    post :save
  end
  get 'search_users' => "users#search_user"
  get 'user/confirm' => "users#confirm"
  get 'search_all_users' => "users#search_all_users"

  devise_for :users, :controllers => 
    {
     :registrations => 'devise_user/registrations',
     sessions: "devise_user/sessions"
    }
  devise_scope :user do
    get "users/:id/add_image" => "devise_user/registrations#add_image"
    patch "users/:id/save_image" => "devise_user/registrations#save_image", as: "upload_profile_pic"
    get 'update_states' => "devise_user/registrations#update_states"
    get 'update_bases' => "devise_user/registrations#update_bases"
  end

  resources :users do
    member do
      get :add_contacts
      post :save_contacts
      get :add_community
      post :save_community
    end
    get :contacts, on: :collection
    post :report_bug, on: :collection
  end
  resources :content_blocks do
    resources :content_block_posts, only: [:index, :create, :new] do
      get :new_reply
      post :save_reply
      get :replies
    end
    member do
      get :index_content_block, controller: :content_block_posts
      get :contacts_and_communities, controller: :content_block_posts
      post :email, controller: :content_block_posts
    end
    post :webhook_notify, controller: :content_block_posts, on: :collection
    post :modify_video_params, controller: :content_block_posts, on: :collection
    get :check_video_upload_status, controller: :content_block_posts, on: :collection
  end
  resources :content_block_posts do
    resources :replies
  end
  resources :replies
  
  namespace :admin do
    resources :tabs do
      resources :sections do
        resources :content_blocks do
          get :get_form_partial, on: :collection 
          get :get_edit_form_partial, on: :member
          get :get_edit_form_partial, on: :collection
        end
      end
    end
    resources :assessments do
      resources :score_ranges do
        post :save_capability, on: :member
      end
      resources :questions do
        post :save_stops, on: :member
      end
    end
    resources :lpds, :path => "lpds" do
      resources :concepts, :path => "concepts"
    end 
    resources :leader_professional_development, :path => "lpds" do
      resources :concepts, :path => "concepts"
    end
  end

  resources :tags
  
  
  get 'onboarding_community_show' => "pages#onboarding_community_show"
  get 'onboarding_community_addcontact' => "pages#onboarding_community_addcontact"
  get 'lpd/:id' => "pages#lpd"
  get 'onboarding_community' => "user_communities#show"
  post "user/community/save" => "user_communities#save_community"
  post "user/allcommunity/save" => "user_communities#save_communities"
  get "user/community/:id/delete" => "user_communities#delete_community"
  get "user/community/:community_id/contact/:contact_id/delete" => "user_communities#delete_community_user"
  get "user/community/:community_id/contact/:contact_id/save" => "user_communities#add_community_user"

  #Template 1
  get 'templates/1-assignment_demands_assessment_1' => "templates#1-assignment_demands_assessment_1"
  get 'templates/1-assignment_demands_assessment_2' => "templates#1-assignment_demands_assessment_2"
  get 'templates/1-assignment_demands_assessment_3' => "templates#1-assignment_demands_assessment_3"
  get 'templates/1-assignment_demands_assessment_4' => "templates#1-assignment_demands_assessment_4"
  get 'templates/1-assignment_demands_assessment_5' => "templates#1-assignment_demands_assessment_5"
  get 'templates/1-assignment_demands_assessment_summary' => "templates#1-assignment_demands_assessment_summary"

  #Template 2
  get 'templates/2-be_a_mentor_1' => "templates#2-be_a_mentor_1"
  get 'templates/2-be_a_mentor_2' => "templates#2-be_a_mentor_2"
  get 'templates/2-be_a_mentor_3' => "templates#2-be_a_mentor_3"
  get 'templates/2-be_a_mentor_4' => "templates#2-be_a_mentor_4"
  get 'templates/2-be_a_mentor_5' => "templates#2-be_a_mentor_5"
  get 'templates/2-be_a_mentor_6' => "templates#2-be_a_mentor_6"
  get 'templates/2-be_a_mentor_7' => "templates#2-be_a_mentor_7"
  get 'templates/2-be_a_mentor_summary' => "templates#2-be_a_mentor_summary"
  
  #Template 3 
  get 'templates/3-command_unit_leader_development_scorecard_1' => 'templates#3-command_unit_leader_development_scorecard_1'
  get 'templates/3-command_unit_leader_development_scorecard_2' => 'templates#3-command_unit_leader_development_scorecard_2'
  get 'templates/3-command_unit_leader_development_scorecard_3' => 'templates#3-command_unit_leader_development_scorecard_3'
  get 'templates/3-command_unit_leader_development_scorecard_4' => 'templates#3-command_unit_leader_development_scorecard_4'
  get 'templates/3-command_unit_leader_development_scorecard_5' => 'templates#3-command_unit_leader_development_scorecard_5'
  get 'templates/3-command_unit_leader_development_scorecard_summary' => 'templates#3-command_unit_leader_development_scorecard_summary'

  #Template 4
  get 'templates/4-daily_leader_observation_planner_1' => 'templates#4-daily_leader_observation_planner_1'
  get 'templates/4-daily_leader_observation_planner_2' => 'templates#4-daily_leader_observation_planner_2'
  get 'templates/4-daily_leader_observation_planner_3' => 'templates#4-daily_leader_observation_planner_3'
  get 'templates/4-daily_leader_observation_planner_summary' => 'templates#4-daily_leader_observation_planner_summary'

  #Template 5
  get 'templates/5-getting_to_know_tool_1' => 'templates#5-getting_to_know_tool_1'
  get 'templates/5-getting_to_know_tool_2' => 'templates#5-getting_to_know_tool_2'
  get 'templates/5-getting_to_know_tool_3' => 'templates#5-getting_to_know_tool_3'
  get 'templates/5-getting_to_know_tool_4' => 'templates#5-getting_to_know_tool_4'
  get 'templates/5-getting_to_know_tool_5' => 'templates#5-getting_to_know_tool_5'
  get 'templates/5-getting_to_know_tool_6' => 'templates#5-getting_to_know_tool_6'
  get 'templates/5-getting_to_know_tool_7' => 'templates#5-getting_to_know_tool_7'
  get 'templates/5-getting_to_know_tool_summary' => 'templates#5-getting_to_know_tool_summary'
  
  #Template 6
  get 'templates/6-individual_plans_for_advancement_1' => 'templates#6-individual_plans_for_advancement_1'
  get 'templates/6-individual_plans_for_advancement_2' => 'templates#6-individual_plans_for_advancement_2'
  get 'templates/6-individual_plans_for_advancement_3' => 'templates#6-individual_plans_for_advancement_3'  
  get 'templates/6-individual_plans_for_advancement_4' => 'templates#6-individual_plans_for_advancement_4' 
  get 'templates/6-individual_plans_for_advancement_5' => 'templates#6-individual_plans_for_advancement_5'  
  get 'templates/6-individual_plans_for_advancement_6' => 'templates#6-individual_plans_for_advancement_6'
  get 'templates/6-individual_plans_for_advancement_summary' => 'templates#6-individual_plans_for_advancement_summary'  

  #Template 7
  get 'templates/7-leadership_selection_guidance_1' => 'templates#7-leadership_selection_guidance_1'
  get 'templates/7-leadership_selection_guidance_2' => 'templates#7-leadership_selection_guidance_2'
  get 'templates/7-leadership_selection_guidance_3' => 'templates#7-leadership_selection_guidance_3'  
  get 'templates/7-leadership_selection_guidance_4' => 'templates#7-leadership_selection_guidance_4' 
  get 'templates/7-leadership_selection_guidance_5' => 'templates#7-leadership_selection_guidance_5'  
  get 'templates/7-leadership_selection_guidance_6' => 'templates#7-leadership_selection_guidance_6'
  get 'templates/7-leadership_selection_guidance_7' => 'templates#7-leadership_selection_guidance_7'  
  get 'templates/7-leadership_selection_guidance_8' => 'templates#7-leadership_selection_guidance_8'
  get 'templates/7-leadership_selection_guidance_summary' => 'templates#7-leadership_selection_guidance_summary'  

  #Template 8
  get 'templates/8-learning_principles_questionaire_a_1' => 'templates#8-learning_principles_questionaire_a_1'
  get 'templates/8-learning_principles_questionaire_a_2' => 'templates#8-learning_principles_questionaire_a_2'
  get 'templates/8-learning_principles_questionaire_a_3' => 'templates#8-learning_principles_questionaire_a_3'
  get 'templates/8-learning_principles_questionaire_a_4' => 'templates#8-learning_principles_questionaire_a_4'
  get 'templates/8-learning_principles_questionaire_a_5' => 'templates#8-learning_principles_questionaire_a_5'
  get 'templates/8-learning_principles_questionaire_a_6' => 'templates#8-learning_principles_questionaire_a_6'
  get 'templates/8-learning_principles_questionaire_a_7' => 'templates#8-learning_principles_questionaire_a_7'
  get 'templates/8-learning_principles_questionaire_a_summary' => 'templates#8-learning_principles_questionaire_a_summary'

  #Template 9
  get 'templates/9-learning_principles_questionaire_b_1' => 'templates#9-learning_principles_questionaire_b_1'
  get 'templates/9-learning_principles_questionaire_b_2' => 'templates#9-learning_principles_questionaire_b_2'
  get 'templates/9-learning_principles_questionaire_b_3' => 'templates#9-learning_principles_questionaire_b_3'
  get 'templates/9-learning_principles_questionaire_b_summary' => 'templates#9-learning_principles_questionaire_b_summary'
  
  #Template 10
  get 'templates/10-training_and_professional_development_1' => 'templates#10-training_and_professional_development_1'
  get 'templates/10-training_and_professional_development_2' => 'templates#10-training_and_professional_development_2'
  get 'templates/10-training_and_professional_development_3' => 'templates#10-training_and_professional_development_3'
  get 'templates/10-training_and_professional_development_4' => 'templates#10-training_and_professional_development_4'

app/models/user.rb
class User < ActiveRecord::Base
  default_scope {includes(:state)}
  default_scope {includes(:country)}
  default_scope {includes(:rank)}
  default_scope {includes(:base_location)}
  
  has_many :contacts_users
  has_many :contacts, through: :contacts_users, class_name: 'User'

  has_many :user_community_contacts, foreign_key: :contact_id
  has_many :user_communities, dependent: :destroy
  has_many :communities, through: :user_community_contacts, source: :user_community
  has_many :content_block_posts, dependent: :destroy
  has_many :templates, class_name: 'UserResourceTemplate'
  has_many :template_types, through: :templates, class_name: 'ResourceTemplate'
  
  #has_many :user_communities, :through => :user_communities_contacts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :state
  belongs_to :country
  belongs_to :rank
  belongs_to :base_location
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable#, :confirmable
   
  validates :first_name, :last_name, :rank_id, :country_id, :state_id, :base_location_id, presence: true
  has_attached_file :image, :styles => { :thumb => "100x100>", :large => "500x500>"}, :default_url => "missing_user.jpeg",  processors: [:cropper]
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  searchkick word_start: [:first_name, :last_name]

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  # after_update :reprocess_image, :if => :cropping?

  scope :search_name, -> (query) { where(
      "LOWER(first_name) like ? or LOWER(last_name) like ? or LOWER(CONCAT(first_name, ' ', last_name)) like ?",
      "%#{query.downcase}%", "%#{query.downcase}%", "%#{query.downcase}%"
  )}

  
  def search_data
    attributes.merge(
      image_url: image.url
    )
  end
  
  def image_url
    self.image.url
  end
  
  def name
    "#{first_name} #{last_name}".titleize
  end

  def rank_last_name
    "#{rank.name} #{last_name}"
  end

  def rank_full_name
    "#{rank.name} #{first_name} #{last_name}"
  end

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def image_geometry(style = :original)
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(image.url(style))
  end



  def reprocess_image
    self.image.reprocess!
    self.save
  end



  #def member_communities
   # UserCommunityContact.where(contact_id: self.id).map{|com| com.user_community }
  #end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  @@per_page = 10
  skip_before_filter :verify_authenticity_token, :only=>[:save_contacts]

  before_filter :authenticate_user!
  before_filter :load_user, only: [:add_contacts, :save_contacts, :add_community, :save_community]
  
  def add_contacts
    user = current_user
    @users = User.includes(:state, :country, :base_location)
                 .where(country_id: user.country_id, 
                        state_id: user.state_id,
                        base_location_id: user.base_location_id)
                 .where.not(id: user.id)
  end
  
  def save_contacts
    contact_ids = params[:contact_ids] || []
    contacts = contact_ids.map{|id| User.find(id)}
    @user.contacts << contacts
    success = @user.save
    respond_to do |format|
      format.json {render json: {success: success} }
      format.js
    end
  end
  
  def add_community
    @contacts = current_user.contacts
  end
  
  def save_community
    @community = UserCommunity.new(name: params[:name], color: "#ef4c7a", status: false, user_id: current_user.id)
    params[:contact_ids] = params[:contact_ids] || []
    if @community.save
      params[:contact_ids] << current_user.id
      @community.contact_ids = params[:contact_ids]
      @community.save
      respond_to do |format|
        format.js { }
      end
    end
  end
  
  def search_user
    user = current_user
    base_location_id = params[:base_location_id].nil? ? user.base_location_id : params[:base_location_id]
    country_id = params[:country_id].nil? ? user.country_id : params[:country_id]
    state_id = params[:state_id].nil? ? user.state_id : params[:state_id]
    rank_id = params[:rank_id].nil? ? user.rank_id : params[:rank_id]
    column_names = [{first_name: :word_start}, {last_name: :word_start}]
    page_number = params[:page_number]
    query = params[:query]
    @users = User.search( "#{query}" , fields: column_names,
      per_page: @@per_page, page: page_number,
      fielddata_fields: [:first_name, :last_name],
      where: {base_location_id: base_location_id,
              country_id: country_id, 
              state_id: state_id,
              rank_id: rank_id
      }
      ).map{|u|({first_name: u.first_name, last_name: u.last_name, id: u.id,
      image_url: u.image.url(:thumb), state_name: u.state.name, country_name: u.country.name, base_location: u.base_location.name}) unless u.id == user.id }.compact
    respond_to do |format|
      format.json {render json: @users }
      format.js
    end
  end

  def search_all_users
    query_where = {}
    query_where[:base_location_id] = params[:base_location_id].to_i if params[:base_location_id].to_i >0
    query_where[:country_id] = params[:country_id].to_i if params[:country_id].to_i >0
    query_where[:state_id] = params[:state_id].to_i if params[:state_id].to_i >0
    query_where[:rank_id] = params[:rank_id].to_i if params[:rank_id].to_i >0

    user = current_user
    column_names = [{first_name: :word_start}, {last_name: :word_start}]
    page_number = params[:page_number]
    query = params[:query]
    @users = User.search( "#{query}" , fields: column_names,
      per_page: @@per_page, page: page_number,
      fielddata_fields: [:first_name, :last_name],
      where: query_where
      ).map{|u|({first_name: u.first_name, last_name: u.last_name, id: u.id,
      image_url: ActionController::Base.helpers.image_path(u.image(:thumb)), rank_name: u.rank.name,state_name: u.state.name, country_name: u.country.name, base_name: u.base_location.name}) unless u.id == user.id }.compact
    
    respond_to do |format|
      format.json {render json: @users }
      format.js
    end
  end

  def contacts
    users = current_user.contacts.search_name(params[:query])
    respond_to do |format|
      format.json{render json: search_results(users) , status: :ok}
    end
  end
  
  def confirm
    token = params[:token]
    user_id = params[:user]
    user = User.where(confirmation_token: token)
    if user.present?
      user[0].id = user_id
      user[0].confirmed_at = Time.now
      user[0].save
      redirect_to root_url
    else
      render plain: 'invalid token'
    end
  end

  def report_bug
    UserMailer.bug_report(current_user, params[:bug][:message]).deliver_later
  end
  
  protected
  def load_user
    @user = User.find_by_id(params[:id])
    unless @user
      render :not_found
    end
  end

  def search_results users
    {results: users.map{|user| {id: user.id, first_name: user.first_name, last_name: user.last_name, email: user.email,
                                image: ActionController::Base.helpers.image_path(user.image(:thumb))} }}
  end

end

app/views/users/_add_community.html.erb
<div class="row pd15">
  <div class="col-xs-12 col-sm-8 col-sm-offset-2">
    <div class="text-center">
      <h3>Join and create communities to share articles, videos, and other content.</h3>
      <h3 class="white">Click below to create a new Community.</h3>
      <%= link_to add_community_user_path(@user), class: "btn-create", remote: true do %>
        <i class="fa fa-plus mr10"></i> Create a new community
      <% end %>
    </div>
    <h4 class="mt35">Your contacts</h4>
    <div class="row">
      <% contacts.each do |user| %>
        <div class="col-xs-6 col-md-4 left-block">
          <div class="user-info">
            <%= image_tag user.image.try(:url), class: 'profile-pic-small' %>
            <div><%= user.name %></div>
            <div><%= "#{user.state.name} #{user.country.name}, #{user.base_location.name}" %> </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="mt35 text-center">
      <%= button_tag "Next", class: 'btn solid-gold' %>
    </div>
    <div class="mt15 text-center">
      <%= link_to "Skip", root_path, class: 'btn btn-link' %>
    </div>
  </div>
</div>

app/views/users/_add_contacts.html.erb
<div class="row pd15 text-center">
  <div class="col-xs-12 col-sm-8 col-sm-offset-2">
    <h3>Congratulations, <%= @user.first_name.capitalize %>! You’ve successfully created a profile.</h3>
    <h3 class="white">Connect with people you know. Select at least 3 contacts to add.</h3>
    <div class="form-group mt35">
      <%= text_field_tag :search, "", class: 'form-control flat-bg', id: "search_input", placeholder: "Search"  %>
    </div>
    <%= form_tag save_contacts_user_path(@user), remote: true, id: "save_contacts" do %>
      <div class="usersContainer">
        <div class="row user-list-header">
          <div class="col-xs-9 left-block">People online</div>
          <div class="col-xs-3">Select</div>
        </div>
        <hr class="light mt15 mb15">
        <div id="usersList">
          <%= render partial: "users/user_search_result", locals: {users: @users} %>
        </div>
        <% if @users && @users.size >= 4  %>
          <div class="text-left text-muted mt15">Scroll to view more</div>
        <% end %>
      </div>
      <div class="mt35">
        <%= submit_tag "Next", class: 'btn solid-gold' %>
      </div>
      <div class="mt15">
        <%= link_to "Skip", "javascript:void(0)", class: 'btn btn-link', onclick: "$('#save_contacts').submit();" %>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#search_input').off('keyup').on('keyup', function(){
    if (this.value.length > 2 ){
      $.ajax({
        method: "GET",
        url: "/search_users",
        dataType: 'script',
        data: { query : this.value }

      })
    }
  });
</script>

app/views/users/_add_photo.html.erb
<div class="row pd15 text-center white">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <h3>Add a profile picture.</h3>
    <div class="row mt35">
      <div class="col-xs-12 col-sm-6 text-right">
        <div class="image-uploader" data-base-height="250" data-base-width="250">
          <div class="image image-holder onboarding">
              <img />
          </div>
        <input id="uploader" type="file" />
        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <%= form_for user, url: upload_profile_pic_path(user), remote: true,  :html => { :multipart => true, id: "image-form"  } do |f| %>
            <a href="javascript:void(0)" class="btn flat-drk filled mb25 active-browse-btn">
              <%= f.file_field :image, onchange: "$('#image-form').submit()", class: "hide-browse-btn"   %>
              <i class="fa fa-desktop mr10"></i>Import from computer</a>
        <% end %>
        <a href="javascript:void(0)" class="btn flat-drk filled mb25 hide-ui-elements"><i class="fa fa-facebook-square mr10"></i>Import from facebook</a>
        <a href="javascript:void(0)" class="btn flat-drk filled mb25 hide-ui-elements"><i class="fa fa-twitter-square mr10"></i>Import from twitter</a>
      </div>
    </div>
    <div class="mt35">
      <%= link_to "Next", "/users/#{user.id}/add_contacts",class: 'btn solid-gold', remote: true %>
    </div>
    <div class="mt15">
      <%= link_to "Skip", add_contacts_user_path(user), class: 'btn btn-link', remote: true %>
    </div>
  </div>
</div>

<script>
  $(function(){
      $("#file").on("change", function(){

      });
  });
</script>

app/views/users/_complete.html.erb
<div class="row pd15">
  <div class="col-xs-12 col-sm-8 col-sm-offset-2">
    <div class="text-center">
      <h3>Great job. All communities can be accessed through the Toolbar.</h3>
      <h3 class="white">You’re all set! Let’s get started!</h3>
      
    </div>
    
    <h3 class="mt35 text-center"><%= community.name %></h3>
    <div class="community-card" style="border: 3px solid #<%= community.color %>">
      <div class="row">
        <% community.contacts.each do |user| %>
          <div class="col-xs-6 left-block text-center">
              <%= image_tag user.image.try(:url), class: 'profile-pic-small' %>
              <div><%= user.name %></div>
          </div>
        <% end %>
      </div>
    </div>
    
    <div class="mt35 text-center">
      <%= link_to "Complete", root_path, class: 'btn solid-gold' %>
    </div>
  </div>
</div>

app/views/users/_create_community.html.erb
<div id="initialCommunityForm" class="row pd15">
  <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <div class="text-center">
        <h3>Join and create communities to share articles, videos, and other content.</h3>
        <h3 class="white">Drag and drop users into your new Community.</h3>
    
        <div id="droparea" class="ui-widget-content">
          <div class="mb35 drag-n-drop-text">DRAG AND DROP USERS HERE</div>
        </div>
      </div>
      <h4 class="mt35">Your contacts</h4>
      <div class="row">
        <% contacts.each do |user| %>
          <div id="user_<%= user.id %>" class="col-xs-6 col-md-4 left-block draggable" data-user-id="<%= user.id %>">
            <div class="user-info">
              <%= image_tag user.image.try(:url), class: 'profile-pic-small' %>
              <div><%= user.name %></div>
              <div><%= "#{user.state.name} #{user.country.name}, #{user.base_location.name}" %> </div>
            </div>
          </div>
        <% end %>
      </div>
      
      <div id="contacts_container"></div>
      
      <div class="mt35 text-center">
        <%= button_tag "Next", class: 'btn solid-gold save-community-next' %>
      </div>

  </div>
</div>

<div id="actualCommunityForm" class="row pd15 hide">
  <div class="col-xs-12 col-sm-8 col-sm-offset-2">
    <%= form_tag save_community_user_path(@user), id: "saveCommunityForm",remote: true do %>
      <div class="text-center">
        <h3>Join and create communities to share articles, videos, and other content.</h3>
        <h3 class="white">Give your new Community a name and assign it a color.</h3>
      </div>
      
      <div class="community-add-name">
        <div class="form-group">
          <%= text_field_tag :name, "", placeholder: "Name", class: 'form-control community_name', data: {errorkey: 'name'} %>
        </div>
      
        <div class="form-group" id="community-color">
          <ul class="community-pallete form-control community_name">
            <li class="blue-color" data-color="#3cc6f4"></li>
            <li class="green-color" data-color="#3bb54b"></li>
            <li class="yellow-color" data-color="#faa726"></li>
            <li class="purple-color" data-color="#b17fb8"></li>
            <li class="red-color" data-color="#b80000"></li>
            <li class="pink-color" data-color="#ef4c7a"></li>
          </ul>
        </div>
        <div id="droparea_placeholder"></div>
      </div>
      
      <div id="contact_ids"></div>
      <div class="mt35 text-center">
        <%= submit_tag "Save", class: 'btn solid-gold' %>
      </div>
      
    <% end %>
  </div>
</div>


<script>
  $('.draggable').draggable({ revert: true });
  $('#droparea').droppable({
    drop: function( event, ui ){
      var user_id = ui.draggable.data('user-id');
      $(this).append(ui.draggable.html());
      if( !$("#contacts_container").find('input[type="hidden"][value='+user_id+']').length > 0 ){
        $('<input>').attr({
          type: 'hidden',
          name: 'contact_ids[]',
          value: user_id,
        }).appendTo('#contacts_container');
      }
      $('#user_'+user_id).draggable( "destroy" ).addClass('hide');
    }
  });
  
  $('.save-community-next').on('click', function(){
    $("#droparea_placeholder").html($('#droparea').html());
    $('.drag-n-drop-text').hide();
    $("#contact_ids").html($('#contacts_container').html());
    $("#initialCommunityForm").addClass('hide slideUp');
    $('#actualCommunityForm').removeClass('hide');
  });
  
  $('.community-pallete li').click(function(event) {
  	var Col = $(this).attr('data-color');
  	//$('#community-color .form-control').css('border-color', ''+Col+'');
  	$('#droparea_placeholder').css('border-color', ''+Col+'');
  });
</script>

app/views/users/_user_search_result.html.erb
<% users.each do |user| %>
  <div class="row">
    <div class="col-xs-9 left-block">
      <div class="user-info">
        <%= image_tag user.image(:thumb), class: 'profile-pic-small' %>
        <div><%= user.name %></div>
        <div><%= "#{user.state.name} #{user.country.name}, #{user.base_location.name}" %> </div>
      </div>
    </div>
    <div class="col-xs-3">
      <%= check_box_tag "contact_ids[]", user.id %>
    </div>
  </div>
<% end %>

app/views/users/_user_search_result_hash.html.erb
<% @users.each do |user| %>
    <div class="row">
      <div class="col-xs-9 left-block">
        <div class="user-info">
          <%= image_tag user[:image_url], class: 'profile-pic-small' %>
          <div><%= user[:name] %></div>
          <div><%= "#{user[:state_name]} #{user[:country_name]}, #{user[:base_location]}" %> </div>
        </div>
      </div>
      <div class="col-xs-3">
        <%= check_box_tag "contact_ids[]", user[:id] %>
      </div>
    </div>
<% end %>

app/views/users/add_community.js.erb
$("#create_community_container").html("<%= j(render partial: 'users/create_community', locals: {contacts: @contacts}) %>");
window.nextStep();

app/views/users/add_contacts.html.erb
<input type="text" id="query" name="query" />

<%= form_tag(save_contacts_user_path(@user), remote: true) do %>
   <% @users.each do |user| %>
     <%= check_box_tag "contacts[]", user.id %>
     <%= user.name %>
   <%end%>
  <div class="div-block">
    <%= button_tag :save %>
  </div>
<%end%>

app/views/users/add_contacts.js.erb
$("#modal-container").modal('hide');
$("#add_contacts_container").html("<%= j(render partial: 'users/add_contacts', locals: {user: @user}) %>");
window.nextStep();

app/views/users/new_community.html.erb
<%= form_tag(users_save_community_path, :remote => true) do %>
  <div>
    <%= label_tag :name %><br>
    <%= text_field_tag :name %>
  </div>
  <div>
    <%= label_tag :color %><br>
    <%= text_field_tag :color %>
  </div>
  <div> 
    <% @contacts.each do |contact| %>
      <% user = contact.user %>
      <%= check_box_tag "contacts[]", user.id %>
      <%= user.name %>
    <%end%>
  </div>
  <div class="div-block">
    <%= button_tag :save %>
  </div>
<%end%>

app/views/users/save_community.js.erb
<% if @community.errors.present? %>
  App.ErrorHandler.add_errors("#createCommunity", "<%= j(raw(@community.errors.to_json)) %>");
<% else %>
  $("#completion_container").html("<%= j(render partial: 'users/complete', locals: {community: @community}) %>");
  window.nextStep();
<% end %>

app/views/users/save_contacts.js.erb
$("#add_community_container").html("<%= j(render partial: 'users/add_community', locals: {contacts: @user.contacts}) %>");
window.nextStep();

app/views/users/search_user.js.erb
$('#usersList').html("<%= j(render partial: 'users/user_search_result_hash', locals: {users: @users}) %>");